name: release
on:
  push:
    # branches:
    #   - main
    tags:
      - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 14.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6

      - run: pnpm install --registry=https://registry.npmmirror.com/

      - run: pnpm run build

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/lisonge/vite-plugin-switch-hosts/blob/${{ github.ref_name }}/CHANGELOG.md) for details.
